# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e10e37144e54cf93ec979a8bf045929359f17404212bafc5d7ee4502f36ca0f0ce02e1f9e1cd0d4de7d0f3f652a11876de5495d50c9028ce9a33948484fe3739

test:
  secret_key_base: 5e8ffb93aebc0fd6efbe59f6a2ba04f070406a79733d50306c78bef0642941ceb7a4db96e9d9d067e00e51f1574ba7dd09e23e14664d0da175e304e09d968c4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
